In [1]:
import numpy as np

Podstawy biblioteki <span style="color:red;font-size:19pt;">**NUMPY**</span>

In [2]:
print("tablice numpy")

tablice numpy


In [3]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
print(np.zeros(8))

[0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
ar = np.ones(11)
print(ar)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [6]:
np.empty(7)

array([ 4.66010016e-310, 0.00000000e+000, 2.41907520e-312,
 2.44029516e-312, 1.18831764e-312, -8.90366852e+232,
 6.92870648e-310])

In [7]:
u = np.arange(1,77,3)
print(u)

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70
 73 76]


In [8]:
print(type(u))

<class 'numpy.ndarray'>


In [9]:
h = [4,6,88,223,12,3]
print(type(h))

<class 'list'>


In [10]:
k = np.linspace(0,10,num=5)
print(k)

[ 0.   2.5  5.   7.5 10. ]


In [11]:
mlista = np.array([45,6,78,24,56,88,34,78,888,44])
print(type(mlista))
print(mlista)

<class 'numpy.ndarray'>
[ 45   6  78  24  56  88  34  78 888  44]


In [12]:
dlista = np.array(h)
print(dlista)

[  4   6  88 223  12   3]


In [13]:
kl = (9,4,5,1,2,3,13,4,2,1)
npk = np.array(kl)
print(npk)
print(type(npk))

[ 9  4  5  1  2  3 13  4  2  1]
<class 'numpy.ndarray'>


In [14]:
zb = {5,1,3,8,65,32,12,-5,0,7,8}
zbk = np.array(zb)
print(zbk)
print(type(zbk))

{32, 1, 65, 3, 0, 5, 7, 8, 12, -5}
<class 'numpy.ndarray'>


In [15]:
nb = [34,2,89,67,11,45,61,45,34,23,68,96,101,4,7,54,87,75,9]
nnb = np.array(nb)
print(nnb)

[ 34   2  89  67  11  45  61  45  34  23  68  96 101   4   7  54  87  75
   9]


In [16]:
nb.sort()
nb

[2, 4, 7, 9, 11, 23, 34, 34, 45, 45, 54, 61, 67, 68, 75, 87, 89, 96, 101]

In [17]:
nnb.sort()
nnb

array([ 2, 4, 7, 9, 11, 23, 34, 34, 45, 45, 54, 61, 67,
 68, 75, 87, 89, 96, 101])

In [18]:
a = np.array([1,5,8,11])
b = np.array([2,89,11,34])
c = np.array([16,29])

z1 = [4,2,6,78]
z2 = [23,4,62,5,6,73]

zwykla = z1+z2
print(zwykla)

[4, 2, 6, 78, 23, 4, 62, 5, 6, 73]


In [19]:
nptab = np.concatenate((a,b,c))
print(nptab)

[ 1  5  8 11  2 89 11 34 16 29]


In [20]:
#utworzenie macierzy
x = np.array([[3,4],[19,6]])
print(x)

[[ 3  4]
 [19  6]]


In [21]:
y = np.array([[7,11],[45,3]])
print(y)

[[ 7 11]
 [45  3]]


In [22]:
zx = [[16,8],[20,5]]
print(zx)

[[16, 8], [20, 5]]


In [23]:
y[1,1]

3

In [25]:
zx[1][1]

5

In [28]:
p = np.concatenate((x,y), axis=0)
p

array([[ 3, 4],
 [19, 6],
 [ 7, 11],
 [45, 3]])

In [29]:
prosta  = np.arange(12)
print(prosta)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [35]:
pp = prosta.reshape(3,4)
print(pp)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [36]:
ret = pp.reshape(12)
print(ret)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [37]:
ar = np.array([1,6,78,9,112,7,80,-5,12,34,55,67,89])
print(ar)

[  1   6  78   9 112   7  80  -5  12  34  55  67  89]


In [39]:
print(ar.shape)

(13,)


In [40]:
print(ar[:4])

[ 1  6 78  9]


In [41]:
print(ar[6:])

[80 -5 12 34 55 67 89]


In [42]:
w = np.array([[1,2,3,4],[99,34,67,56],[21,13,18,22]])
print(w)

[[ 1  2  3  4]
 [99 34 67 56]
 [21 13 18 22]]


In [43]:
print(w[w<5])

[1 2 3 4]


In [44]:
pc = (w>=5)
print(w[pc])

[99 34 67 56 21 13 18 22]


In [45]:
pv = (w%2==0)
print(w[pv])

[ 2  4 34 56 18 22]


In [46]:
cw = w[(w>2) & (w<21)]
print(cw)

[ 3  4 13 18]


In [47]:
sw = w[(w<8) | (w>50)]
print(sw)

[ 1  2  3  4 99 67 56]
