In [1]:
import numpy as np

Podstawy biblioteki <span style="color:red;font-size:19pt;">**NUMPY**</span>

In [3]:
print("tablice numpy")

tablice numpy


In [4]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
print(np.zeros(8))

[0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
ar = np.ones(11)
print(ar)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [7]:
np.empty(7)

array([4.68163205e-310, 0.00000000e+000, 2.41907520e-312, 2.44029516e-312,
 1.18831764e-312, 2.02566915e-322, 4.68163182e-310])

In [9]:
u = np.arange(1,77,3)
print(u)

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70
 73 76]


In [10]:
print(type(u))

<class 'numpy.ndarray'>


In [11]:
h = [4,6,88,223,12,3]
print(type(h))

<class 'list'>


In [12]:
k = np.linspace(0,10,num=5)
print(k)

[ 0.   2.5  5.   7.5 10. ]


In [13]:
mlista = np.array([45,6,78,24,56,88,34,78,888,44])
print(type(mlista))
print(mlista)

<class 'numpy.ndarray'>
[ 45   6  78  24  56  88  34  78 888  44]


In [14]:
dlista = np.array(h)
print(dlista)

[  4   6  88 223  12   3]


In [16]:
kl = (9,4,5,1,2,3,13,4,2,1)
npk = np.array(kl)
print(npk)
print(type(npk))

[ 9  4  5  1  2  3 13  4  2  1]
<class 'numpy.ndarray'>


In [18]:
zb = {5,1,3,8,65,32,12,-5,0,7,8}
zbk = np.array(zb)
print(zbk)
print(type(zbk))

{32, 1, 65, 3, 0, 5, 7, 8, 12, -5}
<class 'numpy.ndarray'>


In [22]:
nb = [34,2,89,67,11,45,61,45,34,23,68,96,101,4,7,54,87,75,9]
nnb = np.array(nb)
print(nnb)

[ 34   2  89  67  11  45  61  45  34  23  68  96 101   4   7  54  87  75
   9]


In [24]:
nb.sort()
nb

[2, 4, 7, 9, 11, 23, 34, 34, 45, 45, 54, 61, 67, 68, 75, 87, 89, 96, 101]

In [26]:
nnb.sort()
nnb

array([ 2, 4, 7, 9, 11, 23, 34, 34, 45, 45, 54, 61, 67,
 68, 75, 87, 89, 96, 101])

In [27]:
a = np.array([1,5,8,11])
b = np.array([2,89,11,34])
c = np.array([16,29])

z1 = [4,2,6,78]
z2 = [23,4,62,5,6,73]

zwykla = z1+z2
print(zwykla)

[4, 2, 6, 78, 23, 4, 62, 5, 6, 73]


In [29]:
nptab = np.concatenate((a,b,c))
print(nptab)

[ 1  5  8 11  2 89 11 34 16 29]
