In [1]:
import numpy as np

In [2]:
arr = np.array([[1.,2.,3.],[6.,8.,9.]])
arr

array([[1., 2., 3.],
 [6., 8., 9.]])

In [3]:
arr*arr

array([[ 1., 4., 9.],
 [36., 64., 81.]])

In [4]:
arr**2

array([[ 1., 4., 9.],
 [36., 64., 81.]])

In [5]:
arr-arr

array([[0., 0., 0.],
 [0., 0., 0.]])

In [6]:
1/arr

array([[1. , 0.5 , 0.33333333],
 [0.16666667, 0.125 , 0.11111111]])

In [7]:
arr**0.5

array([[1. , 1.41421356, 1.73205081],
 [2.44948974, 2.82842712, 3. ]])

In [8]:
arr2 = np.array([[0.,4.,1.],[7.,5.,14.]])
arr2

array([[ 0., 4., 1.],
 [ 7., 5., 14.]])

In [9]:
arr2>arr

array([[False, True, False],
 [ True, False, True]])

In [11]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[2]

array([7, 8, 9])

In [12]:
arr2d[0][2]

3

In [13]:
arr2d[0,2]

3

In [14]:
zl = [[1,2,3],[4,5,6],[7,8,9]]

In [15]:
zl[0][2]

3

In [18]:
#tensor  - tablica 3d
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [19]:
arr3d[0]

array([[1, 2, 3],
 [4, 5, 6]])

In [20]:
arr3d[1]

array([[ 7, 8, 9],
 [10, 11, 12]])

In [21]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [23]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [24]:
arr3d[1,0,1]

8

In [25]:
arr3d.shape

(2, 2, 3)

In [26]:
names = np.array(['Ola','Anna','Piotr','Leon','Kinga','Jan','Jan'])
data = np.random.randn(7,4)
names

array(['Ola', 'Anna', 'Piotr', 'Leon', 'Kinga', 'Jan', 'Jan'], dtype='%lt;U5')

In [27]:
data

array([[-0.27040335, -2.23317187, 1.38811592, 0.96228559],
 [ 0.32178531, -1.39332193, -0.88014382, 0.36789745],
 [-2.67659488, -0.63824631, -0.5967127 , -0.41447111],
 [ 0.2731094 , -1.15990657, 0.60443521, -0.08832735],
 [ 0.13564098, -0.15977384, -1.00880602, -0.68526383],
 [-0.22586557, -0.77239482, -0.37658927, 0.26940979],
 [ 1.66848546, -0.55318176, 0.77711382, -0.81357626]])

In [28]:
names == 'Jan'

array([False, False, False, False, False, True, True])

In [29]:
data[names=="Jan"]

array([[-0.22586557, -0.77239482, -0.37658927, 0.26940979],
 [ 1.66848546, -0.55318176, 0.77711382, -0.81357626]])

In [30]:
data[names=="Jan",2:]

array([[-0.37658927, 0.26940979],
 [ 0.77711382, -0.81357626]])

In [31]:
data[names=="Jan",3]

array([ 0.26940979, -0.81357626])

In [32]:
names != "Jan"

array([ True, True, True, True, True, False, False])

In [33]:
data[~(names=='Jan')]

array([[-0.27040335, -2.23317187, 1.38811592, 0.96228559],
 [ 0.32178531, -1.39332193, -0.88014382, 0.36789745],
 [-2.67659488, -0.63824631, -0.5967127 , -0.41447111],
 [ 0.2731094 , -1.15990657, 0.60443521, -0.08832735],
 [ 0.13564098, -0.15977384, -1.00880602, -0.68526383]])