In [30]:
import numpy as np

In [31]:
arr = np.array([[1.,2.,3.],[6.,8.,9.]])
arr

array([[1., 2., 3.],
 [6., 8., 9.]])

In [32]:
arr*arr

array([[ 1., 4., 9.],
 [36., 64., 81.]])

In [33]:
arr**2

array([[ 1., 4., 9.],
 [36., 64., 81.]])

In [34]:
arr-arr

array([[0., 0., 0.],
 [0., 0., 0.]])

In [35]:
1/arr

array([[1. , 0.5 , 0.33333333],
 [0.16666667, 0.125 , 0.11111111]])

In [36]:
arr**0.5

array([[1. , 1.41421356, 1.73205081],
 [2.44948974, 2.82842712, 3. ]])

In [37]:
arr2 = np.array([[0.,4.,1.],[7.,5.,14.]])
arr2

array([[ 0., 4., 1.],
 [ 7., 5., 14.]])

In [38]:
arr2>arr

array([[False, True, False],
 [ True, False, True]])

In [39]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[2]

array([7, 8, 9])

In [40]:
arr2d[0][2]

3

In [41]:
arr2d[0,2]

3

In [42]:
zl = [[1,2,3],[4,5,6],[7,8,9]]

In [43]:
zl[0][2]

3

In [44]:
#tensor  - tablica 3d
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [45]:
arr3d[0]

array([[1, 2, 3],
 [4, 5, 6]])

In [46]:
arr3d[1]

array([[ 7, 8, 9],
 [10, 11, 12]])

In [47]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [48]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [49]:
arr3d[1,0,1]

8

In [50]:
arr3d.shape

(2, 2, 3)

In [51]:
names = np.array(['Ola','Anna','Piotr','Leon','Kinga','Jan','Jan'])
data = np.random.randn(7,4)
names

array(['Ola', 'Anna', 'Piotr', 'Leon', 'Kinga', 'Jan', 'Jan'], dtype='%lt;U5')

In [52]:
data

array([[-1.25954484, 1.03332258, -0.14268453, 0.62883946],
 [-0.86032325, 0.52739835, 0.72832279, -0.04523347],
 [-0.39051311, -0.46901112, 0.41224983, 0.00423852],
 [ 0.63721799, 1.93756994, 0.13753275, 0.81139015],
 [ 0.02625424, 0.2055589 , -0.90502431, -1.03002669],
 [-0.56756145, 0.21144273, -0.46742104, 0.15793704],
 [-1.4391042 , -0.87842867, -0.90033172, -0.67170237]])

In [53]:
names == 'Jan'

array([False, False, False, False, False, True, True])

In [54]:
data[names=="Jan"]

array([[-0.56756145, 0.21144273, -0.46742104, 0.15793704],
 [-1.4391042 , -0.87842867, -0.90033172, -0.67170237]])

In [55]:
data[names=="Jan",2:]

array([[-0.46742104, 0.15793704],
 [-0.90033172, -0.67170237]])

In [56]:
data[names=="Jan",3]

array([ 0.15793704, -0.67170237])

In [57]:
names != "Jan"

array([ True, True, True, True, True, False, False])

In [58]:
data[~(names=='Jan')]

array([[-1.25954484, 1.03332258, -0.14268453, 0.62883946],
 [-0.86032325, 0.52739835, 0.72832279, -0.04523347],
 [-0.39051311, -0.46901112, 0.41224983, 0.00423852],
 [ 0.63721799, 1.93756994, 0.13753275, 0.81139015],
 [ 0.02625424, 0.2055589 , -0.90502431, -1.03002669]])

In [59]:
cond = names == "Jan"
data[~cond]

array([[-1.25954484, 1.03332258, -0.14268453, 0.62883946],
 [-0.86032325, 0.52739835, 0.72832279, -0.04523347],
 [-0.39051311, -0.46901112, 0.41224983, 0.00423852],
 [ 0.63721799, 1.93756994, 0.13753275, 0.81139015],
 [ 0.02625424, 0.2055589 , -0.90502431, -1.03002669]])

In [60]:
mask = (names == "Jan") | (names == "Kinga")
mask

array([False, False, False, False, True, True, True])

In [61]:
data[mask]

array([[ 0.02625424, 0.2055589 , -0.90502431, -1.03002669],
 [-0.56756145, 0.21144273, -0.46742104, 0.15793704],
 [-1.4391042 , -0.87842867, -0.90033172, -0.67170237]])

In [62]:
data[data<0] = 0
data

array([[0. , 1.03332258, 0. , 0.62883946],
 [0. , 0.52739835, 0.72832279, 0. ],
 [0. , 0. , 0.41224983, 0.00423852],
 [0.63721799, 1.93756994, 0.13753275, 0.81139015],
 [0.02625424, 0.2055589 , 0. , 0. ],
 [0. , 0.21144273, 0. , 0.15793704],
 [0. , 0. , 0. , 0. ]])

In [63]:
data[names != "Leon"] = 88
data

array([[88. , 88. , 88. , 88. ],
 [88. , 88. , 88. , 88. ],
 [88. , 88. , 88. , 88. ],
 [ 0.63721799, 1.93756994, 0.13753275, 0.81139015],
 [88. , 88. , 88. , 88. ],
 [88. , 88. , 88. , 88. ],
 [88. , 88. , 88. , 88. ]])

In [65]:
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i

arr

array([[0., 0., 0., 0.],
 [1., 1., 1., 1.],
 [2., 2., 2., 2.],
 [3., 3., 3., 3.],
 [4., 4., 4., 4.],
 [5., 5., 5., 5.],
 [6., 6., 6., 6.],
 [7., 7., 7., 7.]])

In [66]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
 [3., 3., 3., 3.],
 [0., 0., 0., 0.],
 [6., 6., 6., 6.]])

In [67]:
arr[[-3,-6,-8]]

array([[5., 5., 5., 5.],
 [2., 2., 2., 2.],
 [0., 0., 0., 0.]])

In [68]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0, 1, 2, 3, 4],
 [ 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14]])

In [69]:
arr.T

array([[ 0, 5, 10],
 [ 1, 6, 11],
 [ 2, 7, 12],
 [ 3, 8, 13],
 [ 4, 9, 14]])

In [70]:
arr = np.random.randn(6,3)
arr

array([[-1.06887129e+00, 1.65136851e+00, 2.64334269e-01],
 [ 1.86001043e-01, -1.62111836e+00, -1.27026651e+00],
 [-6.20371046e-01, 2.07451057e-01, 2.71776708e-01],
 [-1.50476686e+00, 1.59476909e+00, 1.00517698e-01],
 [-1.02736471e+00, 5.36724415e-01, 1.08671302e-03],
 [-5.15029578e-01, 9.00334211e-01, 1.31726111e+00]])

In [71]:
arr.T

array([[-1.06887129e+00, 1.86001043e-01, -6.20371046e-01,
 -1.50476686e+00, -1.02736471e+00, -5.15029578e-01],
 [ 1.65136851e+00, -1.62111836e+00, 2.07451057e-01,
 1.59476909e+00, 5.36724415e-01, 9.00334211e-01],
 [ 2.64334269e-01, -1.27026651e+00, 2.71776708e-01,
 1.00517698e-01, 1.08671302e-03, 1.31726111e+00]])

In [72]:
np.dot(arr.T,arr)

array([[ 5.14699947, -5.61019287, -1.51821319],
 [-5.61019287, 9.04004187, 3.89900705],
 [-1.51821319, 3.89900705, 3.50259402]])

In [75]:
arr = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [76]:
arr2 = arr.transpose((1,0,2))
arr2

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [77]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [78]:
arr3 = arr.swapaxes(1,2)
arr3

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [79]:
print(arr.shape)
print(arr2.shape)
print(arr3.shape)

(2, 2, 4)
(2, 2, 4)
(2, 4, 2)
