In [1]:
import numpy as np

In [2]:
arr = np.random.randn(5,4)
arr

array([[-0.54078883, 1.24693461, -0.58705467, -0.79168588],
 [-0.1382848 , -0.63893907, 1.94904542, 0.40481284],
 [-1.22620045, -0.37009753, -0.22118991, -0.68837193],
 [-0.91505224, -1.11770274, 0.16427648, 0.14738775],
 [-2.56199847, 0.17442818, -0.74073695, -0.5680961 ]])

In [3]:
arr.mean()

-0.35096571450027525

In [6]:
arr.mean(axis=1)

array([-0.16814869, 0.3941586 , -0.62646495, -0.43027269, -0.92410084])

In [7]:
arr = np.array([0,2,4,5,6,7,9,11,22])
arr.cumsum()

array([ 0, 2, 6, 11, 17, 24, 33, 44, 66])

In [8]:
arr = np.array([[0,1,2],[6,7,8],[10,15,19]])
arr

array([[ 0, 1, 2],
 [ 6, 7, 8],
 [10, 15, 19]])

In [10]:
arr.cumsum(axis=1)

array([[ 0, 1, 3],
 [ 6, 13, 21],
 [10, 25, 44]])

In [11]:
arr.cumprod(axis=1)

array([[ 0, 0, 0],
 [ 6, 42, 336],
 [ 10, 150, 2850]])

In [12]:
names = np.array(["Jan","Karol","Olga","Leon","Olga","Anna","Jan"])
np.unique(names)

array(['Anna', 'Jan', 'Karol', 'Leon', 'Olga'], dtype='%lt;U5')

In [13]:
sorted(set(names))

['Anna', 'Jan', 'Karol', 'Leon', 'Olga']

In [14]:
#generowanie liczb pseudolosowych
sample = np.random.normal(size=(4,4))
sample

array([[-0.73166725, -1.24210366, 1.05640312, 0.66585118],
 [ 0.51511613, 0.65791783, -2.60383179, 1.59115153],
 [-1.22632924, 0.74226744, 0.62793213, -2.01385998],
 [ 0.77565322, -2.12509732, -0.80559323, -1.08655278]])

In [15]:
from random import normalvariate
N = 1_000_000
%timeit sample = [normalvariate(0,1) for _ in range(N)]
%timeit np.random.normal(size=N)

1.04 s ± 8.33 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
34.9 ms ± 44 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [24]:
np.random.seed(1234)
rng = np.random.RandomState(1234)
rng.randn(10)

array([ 0.47143516, -1.19097569, 1.43270697, -0.3126519 , -0.72058873,
 0.88716294, 0.85958841, -0.6365235 , 0.01569637, -2.24268495])